//using D3D = Vortice.Direct3D;
//using D3D11 = Vortice.Direct3D11;
//using DXGI = Vortice.DXGI;
//using D2D = Vortice.Direct2D1;
//using AlphaMode = Vortice.DXGI.AlphaMode;
//using System.Runtime.CompilerServices;
//using System.Runtime.InteropServices;
//using System.Runtime.Versioning;
//using Windows.Win32.Foundation;
//using Windows.Win32.UI.WindowsAndMessaging;
//using static Windows.Win32.PInvoke;
//using static Windows.Win32.UI.WindowsAndMessaging.PEEK_MESSAGE_REMOVE_TYPE;
//using static Windows.Win32.UI.WindowsAndMessaging.WNDCLASS_STYLES;
//using static Windows.Win32.UI.WindowsAndMessaging.WINDOW_STYLE;
//using static Windows.Win32.UI.WindowsAndMessaging.WINDOW_EX_STYLE;
//using static Windows.Win32.UI.WindowsAndMessaging.SYSTEM_METRICS_INDEX;
//using static Windows.Win32.UI.WindowsAndMessaging.SHOW_WINDOW_CMD;
//using Vortice.DCommon;
//using Vortice.Mathematics;