using System;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.IO;
using FairyGUI.Utils;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Graphics;

using Log = FairyGUI.Utils.Log;
using Rectangle = System.Drawing.RectangleF;

namespace FairyGUI
{
	public class UIPackage
	{
		/// <summary>
		/// Package id. It is generated by the Editor, or set by customId.
		/// </summary>
		public string id { get; private set; }

		/// <summary>
		/// Package name.
		/// </summary>
		public string name { get; private set; }

		/// <summary>
		/// The path relative to the content folder.
		/// </summary>
		public string assetPath { get; private set; }

		List<PackageItem> _items;
		Dictionary<string, PackageItem> _itemsById;
		Dictionary<string, PackageItem> _itemsByName;
		Dictionary<string, string>[] _dependencies;
		string _customId;

		class AtlasSprite
		{
			public PackageItem atlas;
			public Rectangle rect = new Rectangle();
			public bool rotated;
		}
		Dictionary<string, AtlasSprite> _sprites;

		static Dictionary<string, UIPackage> _packageInstById = new Dictionary<string, UIPackage>();
		static Dictionary<string, UIPackage> _packageInstByName = new Dictionary<string, UIPackage>();
		static List<UIPackage> _packageList = new List<UIPackage>();

		internal static int _constructing;

		[ThreadStatic]
		static int _forceTraceDepth;

		internal static bool ForceTraceActive => _forceTraceDepth > 0;

		private static bool ShouldForceTraceForCreateObject(string pkgName, string resName)
		{
			if (string.IsNullOrWhiteSpace(pkgName) || string.IsNullOrWhiteSpace(resName))
				return false;

			if (!string.Equals(pkgName, "UI", StringComparison.Ordinal))
				return false;

			return string.Equals(resName, "主界面_MainUI", StringComparison.Ordinal)
			       || string.Equals(resName, "主界面刘海屏_MainUI", StringComparison.Ordinal);
		}

		public const string URL_PREFIX = "ui://";

		public UIPackage()
		{
			_items = new List<PackageItem>();
			_itemsById = new Dictionary<string, PackageItem>();
			_itemsByName = new Dictionary<string, PackageItem>();
			_sprites = new Dictionary<string, AtlasSprite>();
		}

		/// <summary>
		/// Return a UIPackage with a certain id.
		/// </summary>
		/// <param name="id">ID of the package.</param>
		/// <returns>UIPackage</returns>
		public static UIPackage GetById(string id)
		{
			UIPackage pkg;
			if (_packageInstById.TryGetValue(id, out pkg))
				return pkg;
			else
				return null;
		}

		/// <summary>
		/// Return a UIPackage with a certain name.
		/// </summary>
		/// <param name="name">Name of the package.</param>
		/// <returns>UIPackage</returns>
		public static UIPackage GetByName(string name)
		{
			bool trace = false;
			Stopwatch sw = null;
			try
			{
				trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
				        && MonoShare.Settings.LogErrors
				        && Environment.OSVersion.Platform != PlatformID.Win32NT;

				if (trace)
				{
					sw = Stopwatch.StartNew();
					MonoShare.CMain.SaveLog($"FairyGUI: [GetByName] TryGetValue 开始 name={name}");
				}
			}
			catch
			{
				trace = false;
			}

			UIPackage pkg;
			if (_packageInstByName.TryGetValue(name, out pkg))
			{
				if (trace)
					MonoShare.CMain.SaveLog($"FairyGUI: [GetByName] TryGetValue 命中（{sw?.ElapsedMilliseconds ?? 0}ms） name={name}");
				return pkg;
			}
			else
			{
				if (trace)
					MonoShare.CMain.SaveLog($"FairyGUI: [GetByName] TryGetValue 未命中（{sw?.ElapsedMilliseconds ?? 0}ms） name={name} keys={_packageInstByName.Count}");
				return null;
			}
		}

		/// <summary>
		/// Add a UI package from a path relative to Unity Resources path.
		/// </summary>
		/// <param name="assetPath">Path relative to resources path.</param>
		/// <returns>UIPackage</returns>
		public static UIPackage AddPackage(string assetPath)
		{
			if (_packageInstById.ContainsKey(assetPath))
				return _packageInstById[assetPath];

			byte[] bytes = null;
			IFairyResourceLoader loader = FairyResourceLoader.Current;
			if (loader != null)
			{
				try
				{
					bytes = loader.ReadPackageBytes(assetPath);
				}
				catch (Exception ex)
				{
					Log.Warning("FairyGUI: load package bytes failed: " + assetPath + ", " + ex.Message);
				}
			}

			if (bytes == null)
				bytes = File.ReadAllBytes(Path.Combine(Stage.game.Content.RootDirectory, assetPath + ".fui"));
			if (bytes == null)
				throw new Exception("FairyGUI: Cannot load ui package in '" + assetPath + "'");

			ByteBuffer buffer = new ByteBuffer(bytes);

			UIPackage pkg = new UIPackage();
			pkg.assetPath = assetPath;
			if (!pkg.LoadPackage(buffer))
				return null;

			_packageInstById[pkg.id] = pkg;
			_packageInstByName[pkg.name] = pkg;
			_packageInstById[assetPath] = pkg;
			_packageList.Add(pkg);
			return pkg;
		}

		/// <summary>
		/// Remove a package. All resources in this package will be disposed.
		/// </summary>
		/// <param name="packageIdOrName"></param>
		/// <param name="allowDestroyingAssets"></param>
		public static void RemovePackage(string packageIdOrName)
		{
			UIPackage pkg = null;
			if (!_packageInstById.TryGetValue(packageIdOrName, out pkg))
			{
				if (!_packageInstByName.TryGetValue(packageIdOrName, out pkg))
					throw new Exception("FairyGUI: '" + packageIdOrName + "' is not a valid package id or name.");
			}
			pkg.Dispose();
			_packageInstById.Remove(pkg.id);
			if (pkg._customId != null)
				_packageInstById.Remove(pkg._customId);
			if (pkg.assetPath != null)
				_packageInstById.Remove(pkg.assetPath);
			_packageInstByName.Remove(pkg.name);
			_packageList.Remove(pkg);
		}

		/// <summary>
		/// 
		/// </summary>
		public static void RemoveAllPackages()
		{
			if (_packageInstById.Count > 0)
			{
				UIPackage[] pkgs = _packageList.ToArray();

				foreach (UIPackage pkg in pkgs)
				{
					pkg.Dispose();
				}
			}
			_packageList.Clear();
			_packageInstById.Clear();
			_packageInstByName.Clear();
		}

		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		public static List<UIPackage> GetPackages()
		{
			return _packageList;
		}

		/// <summary>
		/// Create a UI object.
		/// </summary>
		/// <param name="pkgName">Package name.</param>
		/// <param name="resName">Resource name.</param>
		/// <returns>A UI object.</returns>
		public static GObject CreateObject(string pkgName, string resName)
		{
			bool forceTrace = false;
			try
			{
				forceTrace = ShouldForceTraceForCreateObject(pkgName, resName)
				             && MonoShare.Settings.LogErrors
				             && Environment.OSVersion.Platform != PlatformID.Win32NT;

				if (forceTrace)
					_forceTraceDepth++;
			}
			catch
			{
				forceTrace = false;
			}

			try
			{
				bool trace = false;
			Stopwatch totalSw = null;
			try
			{
				trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
				        && MonoShare.Settings.LogErrors
				        && Environment.OSVersion.Platform != PlatformID.Win32NT;

				if (trace)
				{
					totalSw = Stopwatch.StartNew();
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] static 入口 pkgName={pkgName} resName={resName}");
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] static GetByName 开始 pkgName={pkgName}");
				}
			}
			catch
			{
				trace = false;
			}

			UIPackage pkg = GetByName(pkgName);
			if (trace)
				MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] static GetByName 返回（{totalSw?.ElapsedMilliseconds ?? 0}ms） pkg={(pkg == null ? "null" : pkg.name)}");

			if (pkg != null)
			{
				if (trace)
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] static pkg.CreateObject 开始 pkg={pkg.name} resName={resName}");
				return pkg.CreateObject(resName);
			}
			else
				return null;
			}
			finally
			{
				if (forceTrace)
				{
					try
					{
						_forceTraceDepth--;
					}
					catch
					{
					}
				}
			}
		}

		/// <summary>
		///  Create a UI object.
		/// </summary>
		/// <param name="pkgName">Package name.</param>
		/// <param name="resName">Resource name.</param>
		/// <param name="userClass">Custom implementation of this object.</param>
		/// <returns>A UI object.</returns>
		public static GObject CreateObject(string pkgName, string resName, System.Type userClass)
		{
			UIPackage pkg = GetByName(pkgName);
			if (pkg != null)
				return pkg.CreateObject(resName, userClass);
			else
				return null;
		}

		/// <summary>
		/// Create a UI object.
		/// </summary>
		/// <param name="url">Resource url.</param>
		/// <returns>A UI object.</returns>
		public static GObject CreateObjectFromURL(string url)
		{
			PackageItem pi = GetItemByURL(url);
			if (pi != null)
				return pi.owner.CreateObject(pi, null);
			else
				return null;
		}

		/// <summary>
		/// Create a UI object.
		/// </summary>
		/// <param name="url">Resource url.</param>
		/// <param name="userClass">Custom implementation of this object.</param>
		/// <returns>A UI object.</returns>
		public static GObject CreateObjectFromURL(string url, System.Type userClass)
		{
			PackageItem pi = GetItemByURL(url);
			if (pi != null)
				return pi.owner.CreateObject(pi, userClass);
			else
				return null;
		}

		/// <summary>
		/// Get a asset with a certain name.
		/// </summary>
		/// <param name="pkgName">Package name.</param>
		/// <param name="resName">Resource name.</param>
		/// <returns>If resource is atlas, returns NTexture; If resource is sound, returns AudioClip.</returns>
		public static object GetItemAsset(string pkgName, string resName)
		{
			UIPackage pkg = GetByName(pkgName);
			if (pkg != null)
				return pkg.GetItemAsset(resName);
			else
				return null;
		}

		/// <summary>
		/// Get a asset with a certain name.
		/// </summary>
		/// <param name="url">Resource url.</param>
		/// <returns>If resource is atlas, returns NTexture; If resource is sound, returns AudioClip.</returns>
		public static object GetItemAssetByURL(string url)
		{
			PackageItem item = GetItemByURL(url);
			if (item == null)
				return null;

			return item.owner.GetItemAsset(item);
		}

		/// <summary>
		/// Get url of an item in package.
		/// </summary>
		/// <param name="pkgName">Package name.</param>
		/// <param name="resName">Resource name.</param>
		/// <returns>Url.</returns>
		public static string GetItemURL(string pkgName, string resName)
		{
			UIPackage pkg = GetByName(pkgName);
			if (pkg == null)
				return null;

			PackageItem pi;
			if (!pkg._itemsByName.TryGetValue(resName, out pi))
				return null;

			return URL_PREFIX + pkg.id + pi.id;
		}

		public static PackageItem GetItemByURL(string url)
		{
			if (url == null)
				return null;

			int pos1 = url.IndexOf("//");
			if (pos1 == -1)
				return null;

			int pos2 = url.IndexOf('/', pos1 + 2);
			if (pos2 == -1)
			{
				if (url.Length > 13)
				{
					string pkgId = url.Substring(5, 8);
					UIPackage pkg = GetById(pkgId);
					if (pkg != null)
					{
						string srcId = url.Substring(13);
						return pkg.GetItem(srcId);
					}
				}
			}
			else
			{
				string pkgName = url.Substring(pos1 + 2, pos2 - pos1 - 2);
				UIPackage pkg = GetByName(pkgName);
				if (pkg != null)
				{
					string srcName = url.Substring(pos2 + 1);
					return pkg.GetItemByName(srcName);
				}
			}

			return null;
		}

		/// <summary>
		/// 将'ui://包名/组件名'转换为以内部id表达的url格式。如果传入的url本身就是内部id格式，则直接返回。
		/// 同时这个方法还带格式检测，如果传入不正确的url，会返回null。
		/// </summary>
		/// <param name="url"></param>
		/// <returns></returns>
		public static string NormalizeURL(string url)
		{
			if (url == null)
				return null;

			int pos1 = url.IndexOf("//");
			if (pos1 == -1)
				return null;

			int pos2 = url.IndexOf('/', pos1 + 2);
			if (pos2 == -1)
				return url;
			else
			{
				string pkgName = url.Substring(pos1 + 2, pos2 - pos1 - 2);
				string srcName = url.Substring(pos2 + 1);
				return GetItemURL(pkgName, srcName);
			}
		}

		/// <summary>
		/// Set strings source.
		/// </summary>
		/// <param name="source"></param>
		public static void SetStringsSource(XML source)
		{
			TranslationHelper.LoadFromXML(source);
		}

		/// <summary>
		/// Set a custom id for package, then you can use it in GetById.
		/// </summary>
		public string customId
		{
			get { return _customId; }
			set
			{
				if (_customId != null)
					_packageInstById.Remove(_customId);
				_customId = value;
				if (_customId != null)
					_packageInstById[_customId] = this;
			}
		}

		/// <summary>
		/// 获得本包依赖的包的id列表
		/// </summary>
		public Dictionary<string, string>[] dependencies
		{
			get { return _dependencies; }
		}

		bool LoadPackage(ByteBuffer buffer)
		{
			if (buffer.ReadUint() != 0x46475549)
				throw new Exception("FairyGUI: old package format found in '" + assetPath + "'");

			buffer.version = buffer.ReadInt();
			buffer.ReadBool(); //compressed
			id = buffer.ReadString();
			name = buffer.ReadString();
			if (_packageInstById.ContainsKey(id) && name != _packageInstById[id].name)
			{
				Log.Warning("FairyGUI: Package id conflicts, '" + name + "' and '" + _packageInstById[id].name + "'");
				return false;
			}
			buffer.Skip(20);
			int indexTablePos = buffer.position;
			int cnt;

			buffer.Seek(indexTablePos, 4);

			cnt = buffer.ReadInt();
			string[] stringTable = new string[cnt];
			for (int i = 0; i < cnt; i++)
				stringTable[i] = buffer.ReadString();
			buffer.stringTable = stringTable;

			if (buffer.Seek(indexTablePos, 5))
			{
				cnt = buffer.ReadInt();
				for (int i = 0; i < cnt; i++)
				{
					int index = buffer.ReadUshort();
					int len = buffer.ReadInt();
					stringTable[index] = buffer.ReadString(len);
				}
			}

			buffer.Seek(indexTablePos, 1);

			PackageItem pi;

			cnt = buffer.ReadShort();
			for (int i = 0; i < cnt; i++)
			{
				int nextPos = buffer.ReadInt();
				nextPos += buffer.position;

				pi = new PackageItem();
				pi.owner = this;
				pi.type = (PackageItemType)buffer.ReadByte();
				pi.id = buffer.ReadS();
				pi.name = buffer.ReadS();
				buffer.ReadS(); //path
				pi.file = buffer.ReadS();
				pi.exported = buffer.ReadBool();
				pi.width = buffer.ReadInt();
				pi.height = buffer.ReadInt();

				switch (pi.type)
				{
					case PackageItemType.Image:
						{
							pi.objectType = ObjectType.Image;
							int scaleOption = buffer.ReadByte();
							if (scaleOption == 1)
							{
								Rectangle rect = new Rectangle();
								rect.X = buffer.ReadInt();
								rect.Y = buffer.ReadInt();
								rect.Width = buffer.ReadInt();
								rect.Height = buffer.ReadInt();
								pi.scale9Grid = rect;

								pi.tileGridIndice = buffer.ReadInt();
							}
							else if (scaleOption == 2)
								pi.scaleByTile = true;

							buffer.ReadBool(); //smoothing
							break;
						}

					case PackageItemType.MovieClip:
						{
							buffer.ReadBool(); //smoothing
							pi.objectType = ObjectType.MovieClip;
							pi.rawData = buffer.ReadBuffer();
							break;
						}

					case PackageItemType.Font:
						{
							pi.rawData = buffer.ReadBuffer();
							break;
						}

					case PackageItemType.Component:
						{
							int extension = buffer.ReadByte();
							if (extension > 0)
								pi.objectType = (ObjectType)extension;
							else
								pi.objectType = ObjectType.Component;
							pi.rawData = buffer.ReadBuffer();

							UIObjectFactory.ResolvePackageItemExtension(pi);
							break;
						}

					case PackageItemType.Atlas:
					case PackageItemType.Sound:
					case PackageItemType.Misc:
						{
							pi.file = assetPath + "_" + Path.GetFileNameWithoutExtension(pi.file);
							break;
						}
				}
				_items.Add(pi);
				_itemsById[pi.id] = pi;
				if (pi.name != null)
					_itemsByName[pi.name] = pi;

				buffer.position = nextPos;
			}

			buffer.Seek(indexTablePos, 2);

			cnt = buffer.ReadShort();
			for (int i = 0; i < cnt; i++)
			{
				int nextPos = buffer.ReadShort();
				nextPos += buffer.position;

				string itemId = buffer.ReadS();
				pi = _itemsById[buffer.ReadS()];

				AtlasSprite sprite = new AtlasSprite();
				sprite.atlas = pi;
				sprite.rect.X = buffer.ReadInt();
				sprite.rect.Y = buffer.ReadInt();
				sprite.rect.Width = buffer.ReadInt();
				sprite.rect.Height = buffer.ReadInt();
				sprite.rotated = buffer.ReadBool();
				_sprites[itemId] = sprite;

				buffer.position = nextPos;
			}

			if (buffer.Seek(indexTablePos, 3))
			{
				cnt = buffer.ReadShort();
				for (int i = 0; i < cnt; i++)
				{
					int nextPos = buffer.ReadInt();
					nextPos += buffer.position;

					if (_itemsById.TryGetValue(buffer.ReadS(), out pi))
					{
						if (pi.type == PackageItemType.Image)
						{
							pi.pixelHitTestData = new PixelHitTestData();
							pi.pixelHitTestData.Load(buffer);
						}
					}

					buffer.position = nextPos;
				}
			}

			buffer.Seek(indexTablePos, 0);
			cnt = buffer.ReadShort();
			_dependencies = new Dictionary<string, string>[cnt];
			for (int i = 0; i < cnt; i++)
			{
				Dictionary<string, string> kv = new Dictionary<string, string>();
				kv.Add("id", buffer.ReadS());
				kv.Add("name", buffer.ReadS());
				_dependencies[i] = kv;
			}

			return true;
		}

		/// <summary>
		/// 
		/// </summary>
		public void LoadAllAssets()
		{
			int cnt = _items.Count;
			for (int i = 0; i < cnt; i++)
				GetItemAsset(_items[i]);
		}

		void Dispose()
		{
			int cnt = _items.Count;
			for (int i = 0; i < cnt; i++)
			{
				PackageItem pi = _items[i];
				if (pi.type == PackageItemType.Atlas)
				{
					if (pi.texture != null)
					{
						pi.texture.Dispose();
						pi.texture = null;
					}
				}
				else if (pi.type == PackageItemType.Sound)
				{
					if (pi.audioClip != null)
					{
						pi.audioClip.Dispose();
						pi.audioClip = null;
					}

					if (pi.soundEffect != null)
					{
						pi.soundEffect.Dispose();
						pi.soundEffect = null;
					}
				}
			}
			_items.Clear();
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="resName"></param>
		/// <returns></returns>
		public GObject CreateObject(string resName)
		{
			bool trace = false;
			Stopwatch sw = null;
			try
			{
				trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
				        && MonoShare.Settings.LogErrors
				        && Environment.OSVersion.Platform != PlatformID.Win32NT;

				if (trace)
				{
					sw = Stopwatch.StartNew();
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg.CreateObject(string) 入口 pkg={name} resName={resName} itemsByName={_itemsByName?.Count ?? -1}");
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 开始 pkg={name} resName={resName}");
				}
			}
			catch
			{
				trace = false;
			}

			PackageItem pi;
			if (!_itemsByName.TryGetValue(resName, out pi))
			{
				if (trace)
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 未命中（{sw?.ElapsedMilliseconds ?? 0}ms） pkg={name} resName={resName}");
				return null;
			}

			if (trace)
				MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 命中（{sw?.ElapsedMilliseconds ?? 0}ms） pkg={name} resName={resName} itemType={pi?.type}");
			return CreateObject(pi, null);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="resName"></param>
		/// <param name="userClass"></param>
		/// <returns></returns>
		public GObject CreateObject(string resName, System.Type userClass)
		{
			bool trace = false;
			Stopwatch sw = null;
			try
			{
				trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
				        && MonoShare.Settings.LogErrors
				        && Environment.OSVersion.Platform != PlatformID.Win32NT;

				if (trace)
				{
					sw = Stopwatch.StartNew();
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg.CreateObject(type) 入口 pkg={name} resName={resName} userClass={userClass?.FullName} itemsByName={_itemsByName?.Count ?? -1}");
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 开始 pkg={name} resName={resName}");
				}
			}
			catch
			{
				trace = false;
			}

			PackageItem pi;
			if (!_itemsByName.TryGetValue(resName, out pi))
			{
				if (trace)
					MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 未命中（{sw?.ElapsedMilliseconds ?? 0}ms） pkg={name} resName={resName}");
				return null;
			}

			if (trace)
				MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] pkg._itemsByName.TryGetValue 命中（{sw?.ElapsedMilliseconds ?? 0}ms） pkg={name} resName={resName} itemType={pi?.type}");
			return CreateObject(pi, userClass);
		}

		GObject CreateObject(PackageItem item, System.Type userClass)
		{
			Stats.LatestObjectCreation = 0;
			Stats.LatestGraphicsCreation = 0;

            bool trace = false;
            Stopwatch totalSw = null;
            try
            {
                trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
                        && MonoShare.Settings.LogErrors
                        && Environment.OSVersion.Platform != PlatformID.Win32NT;

                if (trace)
                {
                    totalSw = Stopwatch.StartNew();
                    MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] 开始 pkg={name} item={item?.name} type={item?.type}");
                }
            }
            catch
            {
                trace = false;
            }

            if (trace)
            {
                var sw = Stopwatch.StartNew();
                GetItemAsset(item);
                MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] GetItemAsset 完成（{sw.ElapsedMilliseconds}ms） pkg={name} item={item?.name} file={item?.file}");
            }
            else
            {
                GetItemAsset(item);
            }

			GObject g = null;
			if (item.type == PackageItemType.Component)
			{
				if (userClass != null)
					g = (GComponent)Activator.CreateInstance(userClass);
				else
					g = UIObjectFactory.NewObject(item);
			}
			else
				g = UIObjectFactory.NewObject(item);

			if (g == null)
				return null;

            if (trace)
                MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] ConstructFromResource 开始 obj={g.GetType().Name} pkg={name} item={item?.name}");

            _constructing++;
            try
            {
                g.packageItem = item;
                g.ConstructFromResource();
            }
            finally
            {
                _constructing--;
            }

            if (trace)
                MonoShare.CMain.SaveLog($"FairyGUI: [CreateObject] ConstructFromResource 完成（{totalSw?.ElapsedMilliseconds ?? 0}ms） obj={g.GetType().Name} pkg={name} item={item?.name}");
			return g;
		}


		/// <summary>
		/// 
		/// </summary>
		/// <param name="resName"></param>
		/// <returns></returns>
		public object GetItemAsset(string resName)
		{
			PackageItem pi;
			if (!_itemsByName.TryGetValue(resName, out pi))
				return null;

			return GetItemAsset(pi);
		}

		public List<PackageItem> GetItems()
		{
			return _items;
		}

		public PackageItem GetItem(string itemId)
		{
			PackageItem pi;
			if (_itemsById.TryGetValue(itemId, out pi))
				return pi;
			else
				return null;
		}

		public PackageItem GetItemByName(string itemName)
		{
			PackageItem pi;
			if (_itemsByName.TryGetValue(itemName, out pi))
				return pi;
			else
				return null;
		}

		public object GetItemAsset(PackageItem item)
		{
			switch (item.type)
			{
				case PackageItemType.Image:
					if (item.texture == null)
						LoadImage(item);
					return item.texture;

				case PackageItemType.Atlas:
					if (item.texture == null)
						LoadAtlas(item);
					return item.texture;

				case PackageItemType.Sound:
					if (item.audioClip == null)
						LoadSound(item);
					return item.audioClip;

				case PackageItemType.Font:
					if (item.bitmapFont == null)
						LoadFont(item);

					return item.bitmapFont;

				case PackageItemType.MovieClip:
					if (item.frames == null)
						LoadMovieClip(item);

					return item.frames;

				case PackageItemType.Component:
					return item.rawData;

				case PackageItemType.Misc:
					return LoadBinary(item);

				default:
					return null;
			}
		}

		void LoadAtlas(PackageItem item)
		{
            bool trace = false;
            try
            {
                trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
                        && MonoShare.Settings.LogErrors
                        && Environment.OSVersion.Platform != PlatformID.Win32NT;
            }
            catch
            {
                trace = false;
            }

            Stopwatch totalSw = trace ? Stopwatch.StartNew() : null;
            if (trace)
                MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] 开始 pkg={name} file={item?.file}");

			try
			{
				Texture2D tex;
				IFairyResourceLoader loader = FairyResourceLoader.Current;
				if (loader != null)
				{
                    Stopwatch openSw = trace ? Stopwatch.StartNew() : null;
                    if (trace)
                        MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] OpenTextureStream 开始 file={item?.file}");
					using Stream stream = loader.OpenTextureStream(item.file);
                    if (trace && openSw != null)
                        MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] OpenTextureStream 完成（{openSw.ElapsedMilliseconds}ms） file={item?.file}");
#if ANDROID && !REAL_ANDROID
					// 说明：仓库默认 Android 目标在“占位可编译”模式下不强依赖 Mono.Android。
					// Texture2D.FromStream 在 Android 上会引入 Bitmap 相关公开 API，导致缺少 Mono.Android 引用时报错。
					// 真实 Android 构建（REAL_ANDROID）再启用 FromStream 解码。
					tex = new Texture2D(Stage.game.GraphicsDevice, 1, 1);
					tex.SetData(new[] { Microsoft.Xna.Framework.Color.Transparent });
#else
                    Stopwatch decodeSw = trace ? Stopwatch.StartNew() : null;
                    if (trace)
                        MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] Decode 开始 file={item?.file}");
					tex = Texture2D.FromStream(Stage.game.GraphicsDevice, stream);
                    if (trace && decodeSw != null)
                        MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] Decode 完成（{decodeSw.ElapsedMilliseconds}ms） file={item?.file} size={tex?.Width ?? 0}x{tex?.Height ?? 0}");
#endif
				}
				else
				{
					tex = Stage.game.Content.Load<Texture2D>(item.file);
				}
				item.texture = new NTexture(tex, null, tex.Width / item.width, tex.Height / item.height);
                if (trace && totalSw != null)
                    MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] 完成（{totalSw.ElapsedMilliseconds}ms） pkg={name} file={item?.file}");
			}
			catch (Exception ex)
			{
				Log.Warning("FairyGUI: texture '" + item.file + "' not found in " + this.name + ", " + ex.Message);
				item.texture = NTexture.Empty;
                if (trace && totalSw != null)
                    MonoShare.CMain.SaveLog($"FairyGUI: [LoadAtlas] 失败（{totalSw.ElapsedMilliseconds}ms） pkg={name} file={item?.file} err={ex.Message}");
			}
		}

		void LoadImage(PackageItem item)
		{
			AtlasSprite sprite;
			if (_sprites.TryGetValue(item.id, out sprite))
				item.texture = new NTexture((NTexture)GetItemAsset(sprite.atlas), sprite.rect, sprite.rotated);
			else
				item.texture = NTexture.Empty;
		}

		void LoadSound(PackageItem item)
		{
			bool trace = false;
			try
			{
				trace = (ForceTraceActive || MonoShare.FairyGuiHost.MobileMainHudCreateTraceActive)
				        && MonoShare.Settings.LogErrors
				        && Environment.OSVersion.Platform != PlatformID.Win32NT;
			}
			catch
			{
				trace = false;
			}

			Stopwatch totalSw = trace ? Stopwatch.StartNew() : null;
			if (trace)
				MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] 开始 pkg={name} file={item?.file}");

			try
			{
				SoundEffect audioFile;
				IFairyResourceLoader loader = FairyResourceLoader.Current;
				if (loader != null)
				{
					Stopwatch openSw = trace ? Stopwatch.StartNew() : null;
					if (trace)
						MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] OpenSoundStream 开始 file={item?.file}");
					using Stream stream = loader.OpenSoundStream(item.file);
					if (trace && openSw != null)
						MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] OpenSoundStream 完成（{openSw.ElapsedMilliseconds}ms） file={item?.file}");

					Stopwatch decodeSw = trace ? Stopwatch.StartNew() : null;
					if (trace)
						MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] Decode 开始 file={item?.file}");
					audioFile = SoundEffect.FromStream(stream);
					if (trace && decodeSw != null)
						MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] Decode 完成（{decodeSw.ElapsedMilliseconds}ms） file={item?.file}");
					item.soundEffect = audioFile;
				}
				else
				{
					audioFile = Stage.game.Content.Load<SoundEffect>(item.file);
				}

				item.audioClip = audioFile?.CreateInstance();
				if (trace && totalSw != null)
					MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] 完成（{totalSw.ElapsedMilliseconds}ms） pkg={name} file={item?.file}");
			}
			catch (Exception ex)
			{
				Log.Warning("FairyGUI: sound '" + item.file + "' not found in " + this.name + ", " + ex.Message);
				item.audioClip = null;
				if (trace && totalSw != null)
					MonoShare.CMain.SaveLog($"FairyGUI: [LoadSound] 失败（{totalSw.ElapsedMilliseconds}ms） pkg={name} file={item?.file} err={ex.Message}");
			}
		}

		byte[] LoadBinary(PackageItem item)
		{
			try
			{
				IFairyResourceLoader loader = FairyResourceLoader.Current;
				if (loader != null)
				{
					using Stream stream = loader.OpenBinaryStream(item.file);
					using var ms = new MemoryStream();
					stream.CopyTo(ms);
					return ms.ToArray();
				}

				return File.ReadAllBytes(item.file);
			}
			catch (Exception ex)
			{
				Log.Warning("FairyGUI: binary '" + item.file + "' not found in " + this.name + ", " + ex.Message);
				return null;
			}
		}

		void LoadMovieClip(PackageItem item)
		{
			ByteBuffer buffer = item.rawData;

			buffer.Seek(0, 0);

			item.interval = buffer.ReadInt() / 1000f;
			item.swing = buffer.ReadBool();
			item.repeatDelay = buffer.ReadInt() / 1000f;

			buffer.Seek(0, 1);

			int frameCount = buffer.ReadShort();
			item.frames = new MovieClip.Frame[frameCount];

			string spriteId;
			MovieClip.Frame frame;
			AtlasSprite sprite;

			for (int i = 0; i < frameCount; i++)
			{
				int nextPos = buffer.ReadShort();
				nextPos += buffer.position;

				frame = new MovieClip.Frame();
				float fx = buffer.ReadInt();
				float fy = buffer.ReadInt();
				buffer.ReadInt(); //width
				buffer.ReadInt(); //height
				frame.addDelay = buffer.ReadInt() / 1000f;
				spriteId = buffer.ReadS();

				if (spriteId != null && _sprites.TryGetValue(spriteId, out sprite))
				{
					frame.texture = new NTexture((NTexture)GetItemAsset(sprite.atlas), sprite.rect, sprite.rotated,
						new Vector2(item.width, item.height), new Vector2(fx, fy));
				}
				item.frames[i] = frame;

				buffer.position = nextPos;
			}
		}

		void LoadFont(PackageItem item)
		{
			BitmapFont font = new BitmapFont(item);
			item.bitmapFont = font;
			ByteBuffer buffer = item.rawData;

			buffer.Seek(0, 0);

			bool ttf = buffer.ReadBool();
			font.colorEnabled = buffer.ReadBool();
			font.scaleEnabled = buffer.ReadBool();
			buffer.ReadBool();//hasChannel
			int fontSize = buffer.ReadInt();
			int xadvance = buffer.ReadInt();
			int lineHeight = buffer.ReadInt();

			float texScaleX = 1;
			float texScaleY = 1;
			NTexture mainTexture = null;
			AtlasSprite mainSprite = null;
			if (ttf && _sprites.TryGetValue(item.id, out mainSprite))
			{
				mainTexture = (NTexture)GetItemAsset(mainSprite.atlas);
				texScaleX = mainTexture.root.uvRect.Width / mainTexture.width;
				texScaleY = mainTexture.root.uvRect.Height / mainTexture.height;
			}

			buffer.Seek(0, 1);

			BitmapFont.BMGlyph bg;
			int cnt = buffer.ReadInt();
			for (int i = 0; i < cnt; i++)
			{
				int nextPos = buffer.ReadShort();
				nextPos += buffer.position;

				bg = new BitmapFont.BMGlyph();
				char ch = buffer.ReadChar();
				font.AddChar(ch, bg);

				string img = buffer.ReadS();
				int bx = buffer.ReadInt();
				int by = buffer.ReadInt();
				bg.offsetX = buffer.ReadInt();
				bg.offsetY = buffer.ReadInt();
				bg.width = buffer.ReadInt();
				bg.height = buffer.ReadInt();
				bg.advance = buffer.ReadInt();
				bg.channel = buffer.ReadByte();
				if (bg.channel == 1)
					bg.channel = 3;
				else if (bg.channel == 2)
					bg.channel = 2;
				else if (bg.channel == 3)
					bg.channel = 1;

				if (ttf)
				{
					if (mainSprite.rotated)
					{
						bg.uv[0] = new Vector2((float)(by + bg.height + mainSprite.rect.X) * texScaleX,
							1 - (float)(mainSprite.rect.Bottom - bx) * texScaleY);
						bg.uv[1] = new Vector2(bg.uv[0].X - (float)bg.height * texScaleX, bg.uv[0].Y);
						bg.uv[2] = new Vector2(bg.uv[1].X, bg.uv[0].Y + (float)bg.width * texScaleY);
						bg.uv[3] = new Vector2(bg.uv[0].X, bg.uv[2].Y);
					}
					else
					{
						bg.uv[0] = new Vector2((float)(bx + mainSprite.rect.X) * texScaleX,
							1 - (float)(by + bg.height + mainSprite.rect.Y) * texScaleY);
						bg.uv[1] = new Vector2(bg.uv[0].X, bg.uv[0].Y + (float)bg.height * texScaleY);
						bg.uv[2] = new Vector2(bg.uv[0].X + (float)bg.width * texScaleX, bg.uv[1].Y);
						bg.uv[3] = new Vector2(bg.uv[2].X, bg.uv[0].Y);
					}

					bg.lineHeight = lineHeight;
				}
				else
				{
					PackageItem charImg;
					if (_itemsById.TryGetValue(img, out charImg))
					{
						GetItemAsset(charImg);
						charImg.texture.GetUV(bg.uv);
						bg.width = charImg.texture.width;
						bg.height = charImg.texture.height;

						if (mainTexture == null)
							mainTexture = charImg.texture.root;
					}

					if (fontSize == 0)
						fontSize = bg.height;

					if (bg.advance == 0)
					{
						if (xadvance == 0)
							bg.advance = bg.offsetX + bg.width;
						else
							bg.advance = xadvance;
					}

					bg.lineHeight = bg.offsetY < 0 ? bg.height : (bg.offsetY + bg.height);
					if (bg.lineHeight < font.size)
						bg.lineHeight = font.size;
				}

				buffer.position = nextPos;
			}

			font.size = fontSize;
			font.mainTexture = mainTexture;
		}
	}
}
