name: Build Legend of Mir 2 Android
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install Android Workload
        run: dotnet workload install android --source https://api.nuget.org/v3/index.json
        
      - name: Restore dependencies
        run: dotnet restore "Client_MonoGame.Android/Client_MonoGame.Android.csproj"
        
      - name: Publish Android APK
        run: |
          dotnet publish "Client_MonoGame.Android/Client_MonoGame.Android.csproj" -c Release -f net8.0-android /p:CheckEolTargetFramework=false /p:AndroidPackageFormat=apk /p:AndroidBuildApplicationPackage=true -o ./publish_output
        
      - name: List Output Files (Confirming APK)
        run: |
          dir /s ./publish_output
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mir2-android-client-v2
          path: ./publish_output/*.apk
