name: Build Legend of Mir 2
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Server
        run: dotnet publish "Server.MirForms/Server.csproj" -c Release -o ./publish -r win-x64 --self-contained
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mir2-windows-server
          path: ./publish